on:
  schedule:
    - cron: '0 0 * * *'
    # This makes the action to run at the end of every day. Customize this accordingly or you can also trigger this action for GitHub events (Pull, Push). Check the GitHub actions page for that.
  workflow_dispatch:
    # workflow_dispatch allows you to trigger the action any time manually

runs:
  using: "composite"
  steps:
    - run: python ${{ github.action_path }}/basic.py
      shell: bash
