
runs:
  using: "composite"
  steps:
    - run: python -m pip install PyGithub  # Installing dependencies
      shell: bash
    - run: python ${{ github.action_path }}/main-script.py ${{ inputs.gh_token }} ${{ inputs.file_name }} ${{ github.workspace }} ${{ inputs.max_repo_description }}
      shell: bash
